### ISSUE TITLE
Init matrix row-wise

### ISSUE THREAD

**Issue by KCErb** [konovod/linalg#4]
Awesome library!

I sorta expected to be able to do something like

```
m = GMat32.new(3, 4)
m.rows.map! do |row|
end
```

to initialize a matrix row by row instead of element by element. The motivation here is that I have a calculation that I need to do per row which is a little expensive, so it's a shame to have to repeat it.

By the way, just a simple `m.rows` breaks the crystal playground in the above

`BUG: trying to downcast LA::SubMatrix(Float32) <- LA::Matrix(Float32)`

**Comment by konovod** [comment]
Thanks!

`m.rows[i]` returns a `Submatrix` that modifies elements of matrix inplace. So you can do something like 
```crystal
m = GMat32.new(3, 4)

m.rows.each do |row|
  v = (1..4).to_a # complex computation
  row.map_with_index! { |_, i, j| v[j] }
end
```
or just modify row[i,j] elements directly if calculation allows. Sadly, not row[j] because it's a matrix, not just array.

But for initialization, yielding version of `GMat32.rows` could be useful, thanks for idea. In this case it would be possible to initialize like this:
```crystal
m = GMat32.rows(3,4) do |i|
  (1..4).to_a # complex computation
end
```

As for `BUG: trying to downcast` - definitely a problem, I'll investigate it. I haven't tried playground but `pp m.rows` triggers same error in code.

**Comment by KCErb** [comment]
oh nice, calling `map!` on the row inside of an each makes more sense than what I was thinking now that I see it.

Sorry I sorta doubled up on issues. I'll close this out as a Q&A and open a new one to focus on the downcast issue.
